#                 ##    ##  #######  ##    ## ######## ####  ######                     #
#                 ##   ##  ##     ## ###   ## ##        ##  ##    ##                    #
#                 ##  ##   ##     ## ####  ## ##        ##  ##                          #
#                 #####    ##     ## ## ## ## ######    ##  ##   ####                   #
#                 ##  ##   ##     ## ##  #### ##        ##  ##    ##                    #
#                 ##   ##  ##     ## ##   ### ##        ##  ##    ##                    #
#                 ##    ##  #######  ##    ## ##       ####  ######                     #

#########################################################################################
#---------------------------------------------------------------------------------------#
##-------------------------------  Hauptkonfiguration ---------------------------------##
#---------------------------------------------------------------------------------------#
#########################################################################################

#-----------------------------------------------------------  
# Inkludierte Dateien
#-----------------------------------------------------------

# Ordner Zugriffsberechtigungen Extern/Intern
homeassistant:
  allowlist_external_dirs:
    - /config/sensor
    - /config/template

sensor: !include_dir_list sensor
template: !include_dir_list template

#-----------------------------------------------------------  
# MÃ¼ll-Kalender
#-----------------------------------------------------------
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/muell/Abfallkalender.ics"
